import type { MainAppLayoutSurfacesContext } from "@app/hooks/useMainAppLayoutSurfaces";
import type { LayoutNodesOptions } from "@/features/layout/hooks/layoutNodes/types";
import { REMOTE_THREAD_POLL_INTERVAL_MS } from "@app/hooks/useRemoteThreadRefreshOnFocus";

export function buildCodexSurface({
  appSettings,
  workspaces,
  groupedWorkspaces,
  workspaceGroupsCount,
  deletingWorktreeIds,
  newAgentDraftWorkspaceId,
  startingDraftThreadWorkspaceId,
  threadsByWorkspace,
  threadParentById,
  threadStatusById,
  threadResumeLoadingById,
  threadListLoadingByWorkspace,
  threadListPagingByWorkspace,
  threadListCursorByWorkspace,
  pinnedThreadsVersion,
  threadListSortKey,
  onSetThreadListSortKey,
  threadListOrganizeMode,
  onSetThreadListOrganizeMode,
  onRefreshAllThreads,
  activeWorkspace,
  activeWorkspaceId,
  activeThreadId,
  activeItems,
  userInputRequests,
  approvals,
  sidebarRateLimits,
  sidebarAccount,
  homeRateLimits,
  homeAccount,
  enterpriseAiUsage,
  accountSwitching,
  onSwitchAccount,
  onCancelSwitchAccount,
  onDecision,
  onRemember,
  onUserInputSubmit,
  onPlanAccept,
  onPlanSubmitChanges,
  onOpenWorkspaceFileLink,
  activeTokenUsage,
  latestAgentRuns,
  isLoadingLatestAgents,
  localUsageSnapshot,
  isLoadingLocalUsage,
  localUsageError,
  onRefreshLocalUsage,
  usageMetric,
  onUsageMetricChange,
  usageWorkspaceId,
  usageWorkspaceOptions,
  onUsageWorkspaceChange,
  onOpenEnterpriseAiSettings,
  onBeforeComposerSend,
  onOpenCapabilities,
  gitState,
  composerWorkspaceState,
  composerQuickActions,
  worktreeState,
  sidebarHandlers,
  displayNodes,
  threadPinning,
  workspaceDrop,
  threadNavigation,
  pullRequestComposer,
  openAppIconById,
  handleAddWorkspace,
  openWorkspaceFromUrlPrompt,
  handleAddAgent,
  handleAddWorktreeAgent,
  handleAddCloneAgent,
  handleOpenThreadLink,
  handleSelectOpenAppId,
  handleCopyThread,
  handleToggleTerminalWithFocus,
  launchScriptState,
  launchScriptsState,
  models,
  selectedModelId,
  onSelectModel,
  collaborationModes,
  selectedCollaborationModeId,
  onSelectCollaborationMode,
  reasoningOptions,
  selectedEffort,
  onSelectEffort,
  selectedServiceTier,
  reasoningSupported,
  codexArgsOptions,
  selectedCodexArgsOverride,
  onSelectCodexArgsOverride,
  accessMode,
  onSelectAccessMode,
  skills,
  apps,
  prompts,
  composerInputRef,
  composerEditorSettings,
  composerEditorExpanded,
  onToggleComposerEditorExpanded,
  composerContextActions,
  reviewPrompt,
  closeReviewPrompt,
  showPresetStep,
  choosePreset,
  highlightedPresetIndex,
  setHighlightedPresetIndex,
  highlightedBranchIndex,
  setHighlightedBranchIndex,
  highlightedCommitIndex,
  setHighlightedCommitIndex,
  handleReviewPromptKeyDown,
  selectBranch,
  selectBranchAtIndex,
  confirmBranch,
  selectCommit,
  selectCommitAtIndex,
  confirmCommit,
  updateCustomInstructions,
  confirmCustom,
  handleComposerSendWithDraftStart,
  interruptTurn,
  terminalOpen,
  isCompact,
  activeTab,
  setActiveTab,
  tabletTab,
  showMobilePollingFetchStatus,
  appModalsAboutOpen,
  updaterState,
  startUpdate,
  cancelUpdate,
  dismissUpdate,
  postUpdateNotice,
  dismissPostUpdateNotice,
  errorToasts,
  dismissErrorToast,
  showDebugButton,
  handleDebugClick,
}: MainAppLayoutSurfacesContext): LayoutNodesOptions["primary"] {
  // File attachments are local-path only: unsupported in remote mode (the path
  // is unreachable to the daemon) and in the PR-review composer (its send path
  // launches a review and does not carry file paths). Gate them off in both so
  // attachments can never be silently dropped at send.
  const fileAttachmentsEnabled =
    appSettings.backendMode !== "remote" &&
    !pullRequestComposer.isPullRequestComposer;
  return {
    sidebarProps: {
      workspaces,
      groupedWorkspaces,
      hasWorkspaceGroups: workspaceGroupsCount > 0,
      deletingWorktreeIds,
      newAgentDraftWorkspaceId,
      startingDraftThreadWorkspaceId,
      threadsByWorkspace,
      threadParentById,
      threadStatusById,
      threadListLoadingByWorkspace,
      threadListPagingByWorkspace,
      threadListCursorByWorkspace,
      pinnedThreadsVersion,
      threadListSortKey,
      onSetThreadListSortKey,
      threadListOrganizeMode,
      onSetThreadListOrganizeMode,
      onRefreshAllThreads,
      activeWorkspaceId,
      activeThreadId,
      userInputRequests,
      accountRateLimits: sidebarRateLimits,
      usageShowRemaining: appSettings.usageShowRemaining,
      accountInfo: sidebarAccount,
      enterpriseAi: appSettings.enterpriseAi,
      onSwitchAccount,
      onCancelSwitchAccount,
      accountSwitching,
      onOpenSettings: sidebarHandlers.onOpenSettings,
      onOpenCapabilities,
      onOpenEnterpriseAiSettings,
      onOpenDebug: handleDebugClick,
      showDebugButton,
      onAddWorkspace: handleAddWorkspace,
      onSelectHome: sidebarHandlers.onSelectHome,
      onSelectWorkspace: sidebarHandlers.onSelectWorkspace,
      onAddAgent: handleAddAgent,
      onAddWorktreeAgent: handleAddWorktreeAgent,
      onAddCloneAgent: handleAddCloneAgent,
      onToggleWorkspaceCollapse: sidebarHandlers.onToggleWorkspaceCollapse,
      onSelectThread: sidebarHandlers.onSelectThread,
      onDeleteThread: sidebarHandlers.onDeleteThread,
      onSyncThread: sidebarHandlers.onSyncThread,
      pinThread: threadPinning.pinThread,
      unpinThread: threadPinning.unpinThread,
      isThreadPinned: threadPinning.isThreadPinned,
      getPinTimestamp: threadPinning.getPinTimestamp,
      getThreadArgsBadge: threadPinning.getThreadArgsBadge,
      onRenameThread: sidebarHandlers.onRenameThread,
      onDeleteWorkspace: sidebarHandlers.onDeleteWorkspace,
      onDeleteWorktree: sidebarHandlers.onDeleteWorktree,
      onLoadOlderThreads: sidebarHandlers.onLoadOlderThreads,
      onReloadWorkspaceThreads: sidebarHandlers.onReloadWorkspaceThreads,
      workspaceDropTargetRef: workspaceDrop.workspaceDropTargetRef,
      isWorkspaceDropActive: workspaceDrop.isWorkspaceDropActive,
      workspaceDropText: workspaceDrop.workspaceDropText,
      onWorkspaceDragOver: workspaceDrop.onWorkspaceDragOver,
      onWorkspaceDragEnter: workspaceDrop.onWorkspaceDragEnter,
      onWorkspaceDragLeave: workspaceDrop.onWorkspaceDragLeave,
      onWorkspaceDrop: workspaceDrop.onWorkspaceDrop,
    },
    messagesProps: {
      items: activeItems,
      threadId: activeThreadId ?? null,
      workspaceId: activeWorkspace?.id ?? null,
      workspacePath: activeWorkspace?.path ?? null,
      openTargets: appSettings.openAppTargets,
      openAppIconById,
      selectedOpenAppId: appSettings.selectedOpenAppId,
      onSelectOpenAppId: handleSelectOpenAppId,
      codeBlockCopyUseModifier: appSettings.composerCodeBlockCopyUseModifier,
      showMessageFilePath: appSettings.showMessageFilePath,
      userInputRequests,
      onUserInputSubmit,
      onPlanAccept,
      onPlanSubmitChanges,
      onOpenThreadLink: handleOpenThreadLink,
      onOpenWorkspaceFileLink,
      onQuoteMessage: composerWorkspaceState.canInsertComposerText
        ? composerWorkspaceState.handleInsertComposerText
        : undefined,
      isThinking: composerWorkspaceState.isProcessing,
      isLoadingMessages: activeThreadId
        ? threadResumeLoadingById[activeThreadId] ?? false
        : false,
      processingStartedAt: activeThreadId
        ? threadStatusById[activeThreadId]?.processingStartedAt ?? null
        : null,
      lastDurationMs: activeThreadId
        ? threadStatusById[activeThreadId]?.lastDurationMs ?? null
        : null,
      showPollingFetchStatus: showMobilePollingFetchStatus,
      pollingIntervalMs: REMOTE_THREAD_POLL_INTERVAL_MS,
    },
    composerProps: composerWorkspaceState.showComposer
      ? {
          onSend: handleComposerSendWithDraftStart,
          onBeforeSend: onBeforeComposerSend,
          onStop: interruptTurn,
          canStop: composerWorkspaceState.canInterrupt,
          disabled: composerWorkspaceState.isReviewing,
          onFileAutocompleteActiveChange: composerWorkspaceState.setFileAutocompleteActive,
          contextUsage: activeTokenUsage,
          queuedMessages: composerWorkspaceState.activeQueue,
          queuePausedReason: composerWorkspaceState.queuePausedReason,
          sendLabel: pullRequestComposer.composerSendLabel ?? "Send",
          steerAvailable: composerWorkspaceState.steerAvailable,
          followUpMessageBehavior: appSettings.followUpMessageBehavior,
          composerFollowUpHintEnabled: appSettings.composerFollowUpHintEnabled,
          isProcessing: composerWorkspaceState.isProcessing,
          draftText: composerWorkspaceState.activeDraft,
          onDraftChange: composerWorkspaceState.handleDraftChange,
          attachedImages: composerWorkspaceState.activeImages,
          onPickImages: composerWorkspaceState.pickImages,
          onAttachImages: composerWorkspaceState.attachImages,
          onRemoveImage: composerWorkspaceState.removeImage,
          attachedFiles: fileAttachmentsEnabled
            ? composerWorkspaceState.activeFiles
            : [],
          onPickFiles: fileAttachmentsEnabled
            ? composerWorkspaceState.pickFiles
            : undefined,
          onAttachFiles: fileAttachmentsEnabled
            ? composerWorkspaceState.attachFiles
            : undefined,
          onRemoveFile: composerWorkspaceState.removeFile,
          canAttachFiles: fileAttachmentsEnabled,
          prefillDraft: composerWorkspaceState.prefillDraft,
          onPrefillHandled: (id) => {
            if (composerWorkspaceState.prefillDraft?.id === id) {
              composerWorkspaceState.setPrefillDraft(null);
            }
          },
          insertText: composerWorkspaceState.composerInsert,
          onInsertHandled: (id) => {
            if (composerWorkspaceState.composerInsert?.id === id) {
              composerWorkspaceState.setComposerInsert(null);
            }
          },
          onEditQueued: composerWorkspaceState.handleEditQueued,
          onDeleteQueued: composerWorkspaceState.handleDeleteQueued,
          collaborationModes,
          selectedCollaborationModeId,
          onSelectCollaborationMode,
          models,
          selectedModelId,
          onSelectModel,
          reasoningOptions,
          selectedEffort,
          onSelectEffort,
          selectedServiceTier,
          reasoningSupported,
          codexArgsOptions,
          selectedCodexArgsOverride,
          onSelectCodexArgsOverride,
          accessMode,
          onSelectAccessMode,
          skills,
          appsEnabled: appSettings.experimentalAppsEnabled,
          apps,
          prompts,
          files: composerWorkspaceState.files,
          textareaRef: composerInputRef,
          historyKey: activeWorkspace?.id ?? null,
          editorSettings: composerEditorSettings,
          editorExpanded: composerEditorExpanded,
          onToggleEditorExpanded: onToggleComposerEditorExpanded,
          contextActions: composerContextActions,
          quickActions: composerQuickActions,
          reviewPrompt,
          onReviewPromptClose: closeReviewPrompt,
          onReviewPromptShowPreset: showPresetStep,
          onReviewPromptChoosePreset: choosePreset,
          highlightedPresetIndex,
          onReviewPromptHighlightPreset: setHighlightedPresetIndex,
          highlightedBranchIndex,
          onReviewPromptHighlightBranch: setHighlightedBranchIndex,
          highlightedCommitIndex,
          onReviewPromptHighlightCommit: setHighlightedCommitIndex,
          onReviewPromptKeyDown: handleReviewPromptKeyDown,
          onReviewPromptSelectBranch: selectBranch,
          onReviewPromptSelectBranchAtIndex: selectBranchAtIndex,
          onReviewPromptConfirmBranch: confirmBranch,
          onReviewPromptSelectCommit: selectCommit,
          onReviewPromptSelectCommitAtIndex: selectCommitAtIndex,
          onReviewPromptConfirmCommit: confirmCommit,
          onReviewPromptUpdateCustomInstructions: updateCustomInstructions,
          onReviewPromptConfirmCustom: confirmCustom,
        }
      : null,
    approvalToastsProps: {
      approvals,
      workspaces,
      onDecision,
      onRemember,
    },
    updateToastProps: {
      state: appModalsAboutOpen ? { stage: "idle" as const } : updaterState,
      onUpdate: startUpdate,
      onCancel: cancelUpdate,
      onDismiss: dismissUpdate,
      postUpdateNotice,
      onDismissPostUpdateNotice: dismissPostUpdateNotice,
    },
    errorToastsProps: {
      toasts: errorToasts,
      onDismiss: dismissErrorToast,
    },
    homeProps: {
      onAddWorkspace: handleAddWorkspace,
      onAddWorkspaceFromUrl: openWorkspaceFromUrlPrompt,
      latestAgentRuns,
      isLoadingLatestAgents,
      localUsageSnapshot,
      isLoadingLocalUsage,
      localUsageError,
      onRefreshLocalUsage,
      usageMetric,
      onUsageMetricChange,
      usageWorkspaceId,
      usageWorkspaceOptions,
      onUsageWorkspaceChange,
      accountRateLimits: homeRateLimits,
      enterpriseAiUsage,
      usageShowRemaining: appSettings.usageShowRemaining,
      accountInfo: homeAccount,
      onSelectThread: (workspaceId, threadId) => {
        threadNavigation.exitDiffView();
        threadNavigation.clearDraftState();
        threadNavigation.selectWorkspace(workspaceId);
        threadNavigation.setActiveThreadId(threadId, workspaceId);
        if (isCompact) {
          setActiveTab("codex");
        }
      },
    },
    mainHeaderProps: activeWorkspace
      ? {
          workspace: activeWorkspace,
          parentName: worktreeState.activeParentWorkspace?.name ?? null,
          worktreeLabel: worktreeState.worktreeLabel,
          worktreeRename: worktreeState.worktreeRename ?? undefined,
          disableBranchMenu: worktreeState.isWorktreeWorkspace,
          parentPath: worktreeState.activeParentWorkspace?.path ?? null,
          worktreePath: worktreeState.isWorktreeWorkspace ? activeWorkspace.path : null,
          openTargets: appSettings.openAppTargets,
          openAppIconById,
          selectedOpenAppId: appSettings.selectedOpenAppId,
          onSelectOpenAppId: handleSelectOpenAppId,
          branchName: gitState.gitStatus.branchName || "unknown",
          branches: gitState.branches,
          onCheckoutBranch: gitState.handleCheckoutBranch,
          onCreateBranch: gitState.handleCreateBranch,
          canCopyThread: activeItems.length > 0,
          onCopyThread: handleCopyThread,
          onToggleTerminal: handleToggleTerminalWithFocus,
          isTerminalOpen: terminalOpen,
          showTerminalButton: !isCompact,
          showWorkspaceTools: !isCompact,
          launchScript: launchScriptState.launchScript,
          launchScriptEditorOpen: launchScriptState.editorOpen,
          launchScriptDraft: launchScriptState.draftScript,
          launchScriptSaving: launchScriptState.isSaving,
          launchScriptError: launchScriptState.error,
          onRunLaunchScript: launchScriptState.onRunLaunchScript,
          onOpenLaunchScriptEditor: launchScriptState.onOpenEditor,
          onCloseLaunchScriptEditor: launchScriptState.onCloseEditor,
          onLaunchScriptDraftChange: launchScriptState.onDraftScriptChange,
          onSaveLaunchScript: launchScriptState.onSaveLaunchScript,
          launchScriptsState,
          extraActionsNode: displayNodes.mainHeaderActionsNode,
        }
      : null,
    desktopTopbarProps: {
      showBackToChat: gitState.centerMode === "diff",
      onExitDiff: () => {
        gitState.setCenterMode("chat");
        gitState.setSelectedDiffPath(null);
      },
    },
    tabletNavProps: {
      activeTab: tabletTab,
      onSelect: setActiveTab,
    },
    tabBarProps: {
      activeTab,
      onSelect: (tab) => {
        if (tab === "home") {
          threadNavigation.resetPullRequestSelection();
          threadNavigation.clearDraftState();
          threadNavigation.selectHome();
          return;
        }
        setActiveTab(tab);
      },
    },
  };
}
