import type { ConversationItem } from "@/types";
import {
  imageGenerationIdsMatch,
  normalizeItem,
  prepareThreadItems,
  upsertItem,
} from "@utils/threadItems";
import type { ThreadAction, ThreadState } from "../useThreadsReducer";
import {
  addSummaryBoundary,
  dropLatestLocalReviewStart,
  ensureUniqueReviewId,
  extractRenameText,
  findMatchingReview,
  isDuplicateReviewById,
  looksAutoGeneratedThreadName,
  maybeRenameThreadFromAgent,
  mergeStreamingText,
  prefersUpdatedSort,
} from "./common";

function findGeneratedImageTextAnchorIndex(
  list: ConversationItem[],
  item: ConversationItem,
): number {
  if (item.kind !== "imageGeneration") {
    return -1;
  }

  const pathTokens = [item.savedPath, item.imageSrc].filter(
    (value): value is string =>
      typeof value === "string" &&
      value.trim().length > 0 &&
      !value.startsWith("data:"),
  );
  if (pathTokens.length === 0) {
    return -1;
  }

  const tokens = new Set(pathTokens.map((value) => value.trim()));
  const callId = item.id.trim();
  if (callId.length > 0) {
    tokens.add(callId);
    if (callId.startsWith("call_")) {
      tokens.add(`_call_${callId.slice("call_".length)}`);
    }
  }

  return list.findIndex((entry) => {
    if (entry.kind !== "message") {
      return false;
    }
    return [...tokens].some((token) => entry.text.includes(token));
  });
}

function pathBelongsToThreadGeneratedImages(path: string, threadId: string) {
  const parts = path.replace(/\\/g, "/").split("/").filter(Boolean);
  const generatedImagesIndex = parts.findIndex((part) =>
    /^generated[_-]images$/i.test(part),
  );
  return (
    generatedImagesIndex >= 0 &&
    parts[generatedImagesIndex + 1] === threadId
  );
}

function isThreadScopedGeneratedImageArtifact(
  item: ConversationItem,
  threadId: string,
) {
  if (item.kind !== "imageGeneration") {
    return false;
  }
  return [item.savedPath, item.imageSrc].some(
    (value) =>
      typeof value === "string" &&
      value.trim().length > 0 &&
      !value.startsWith("data:") &&
      pathBelongsToThreadGeneratedImages(value.trim(), threadId),
  );
}

function getItemCreatedAt(item: ConversationItem) {
  return "createdAt" in item &&
    typeof item.createdAt === "number" &&
    Number.isFinite(item.createdAt)
    ? item.createdAt
    : null;
}

function insertByCreatedAt(list: ConversationItem[], item: ConversationItem) {
  const itemCreatedAt = getItemCreatedAt(item);
  if (itemCreatedAt === null) {
    return [...list, item];
  }
  const insertIndex = list.findIndex((entry) => {
    const entryCreatedAt = getItemCreatedAt(entry);
    return entryCreatedAt !== null && entryCreatedAt > itemCreatedAt;
  });
  if (insertIndex < 0) {
    return [...list, item];
  }
  return [...list.slice(0, insertIndex), item, ...list.slice(insertIndex)];
}

export function reduceThreadItems(state: ThreadState, action: ThreadAction): ThreadState {
  switch (action.type) {
    case "addAssistantMessage": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const message: ConversationItem = {
        id: `${Date.now()}-assistant`,
        kind: "message",
        role: "assistant",
        text: action.text,
        createdAt: action.timestamp ?? Date.now(),
      };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems([...list, message], { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    case "appendAgentDelta": {
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: mergeStreamingText(existing.text, action.delta),
        };
      } else {
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.delta,
          createdAt: action.timestamp ?? Date.now(),
        });
      }
      const updatedItems = prepareThreadItems(list, { maxItemsPerThread: state.maxItemsPerThread });
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "completeAgentMessage": {
      const hasText = action.text.trim().length > 0;
      const list = [...(state.itemsByThread[action.threadId] ?? [])];
      const index = list.findIndex((msg) => msg.id === action.itemId);
      if (index >= 0 && list[index].kind === "message") {
        const existing = list[index];
        list[index] = {
          ...existing,
          text: hasText ? action.text : existing.text,
          createdAt: existing.createdAt ?? action.timestamp ?? Date.now(),
        };
      } else {
        if (!hasText) {
          return state;
        }
        list.push({
          id: action.itemId,
          kind: "message",
          role: "assistant",
          text: action.text,
          createdAt: action.timestamp ?? Date.now(),
        });
      }
      const updatedItems = prepareThreadItems(list, { maxItemsPerThread: state.maxItemsPerThread });
      const nextThreadsByWorkspace = maybeRenameThreadFromAgent({
        workspaceId: action.workspaceId,
        threadId: action.threadId,
        items: updatedItems,
        itemId: action.itemId,
        hasCustomName: action.hasCustomName,
        threadsByWorkspace: state.threadsByWorkspace,
      });
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "upsertItem": {
      let list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const isUserMessage = item.kind === "message" && item.role === "user";
      const hadUserMessage = isUserMessage
        ? list.some((entry) => entry.kind === "message" && entry.role === "user")
        : false;
      const renameText = isUserMessage ? extractRenameText(item.text) : "";
      if (
        item.kind === "review" &&
        item.state === "started" &&
        !item.id.startsWith("review-start-")
      ) {
        list = dropLatestLocalReviewStart(list);
      }
      if (item.kind === "review" && isDuplicateReviewById(list, item)) {
        return state;
      }
      if (item.kind === "review") {
        const existing = findMatchingReview(list, item);
        if (existing && existing.id !== item.id) {
          return state;
        }
      }
      const nextItem = ensureUniqueReviewId(list, item);
      const updatedItems = prepareThreadItems(upsertItem(list, nextItem), { maxItemsPerThread: state.maxItemsPerThread });
      let nextThreadsByWorkspace = state.threadsByWorkspace;
      if (isUserMessage) {
        const threads = state.threadsByWorkspace[action.workspaceId] ?? [];
        const textValue = renameText;
        const updatedThreads = threads.map((thread) => {
          if (thread.id !== action.threadId) {
            return thread;
          }
          const looksAutoGenerated = looksAutoGeneratedThreadName(thread.name);
          const shouldRename =
            !hadUserMessage &&
            textValue.length > 0 &&
            looksAutoGenerated &&
            !action.hasCustomName;
          const nextName =
            shouldRename && textValue.length > 38
              ? `${textValue.slice(0, 38)}…`
              : shouldRename
                ? textValue
                : thread.name;
          return { ...thread, name: nextName };
        });
        const bumpedThreads =
          prefersUpdatedSort(state, action.workspaceId) && updatedThreads.length
            ? [
                ...updatedThreads.filter((thread) => thread.id === action.threadId),
                ...updatedThreads.filter((thread) => thread.id !== action.threadId),
              ]
            : updatedThreads;
        nextThreadsByWorkspace = {
          ...state.threadsByWorkspace,
          [action.workspaceId]: bumpedThreads,
        };
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: updatedItems,
        },
        threadsByWorkspace: nextThreadsByWorkspace,
      };
    }
    case "hydrateGeneratedImageItem": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const item = normalizeItem(action.item);
      const conversationAnchor =
        item.kind === "imageGeneration"
          ? list.find(
              (entry) =>
                entry.kind === "imageGeneration" &&
                imageGenerationIdsMatch(entry.id, item.id),
            )
          : undefined;
      if (!conversationAnchor) {
        const textAnchorIndex = findGeneratedImageTextAnchorIndex(list, item);
        if (textAnchorIndex >= 0) {
          return {
            ...state,
            itemsByThread: {
              ...state.itemsByThread,
              [action.threadId]: prepareThreadItems(
                [
                  ...list.slice(0, textAnchorIndex),
                  item,
                  ...list.slice(textAnchorIndex),
                ],
                { maxItemsPerThread: state.maxItemsPerThread },
              ),
            },
          };
        }
        if (!isThreadScopedGeneratedImageArtifact(item, action.threadId)) {
          return state;
        }
        return {
          ...state,
          itemsByThread: {
            ...state.itemsByThread,
            [action.threadId]: prepareThreadItems(
              insertByCreatedAt(list, item),
              {
                maxItemsPerThread: state.maxItemsPerThread,
              },
            ),
          },
        };
      }
      const anchoredItem =
        conversationAnchor.id === item.id ? item : { ...item, id: conversationAnchor.id };
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(upsertItem(list, anchoredItem), {
            maxItemsPerThread: state.maxItemsPerThread,
          }),
        },
      };
    }
    case "setThreadItems":
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(action.items, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    case "appendReasoningSummary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: mergeStreamingText(
          "summary" in base ? base.summary : "",
          action.delta,
        ),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    case "appendReasoningSummaryBoundary": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        summary: addSummaryBoundary("summary" in base ? base.summary : ""),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    case "appendReasoningContent": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "reasoning"
          ? (list[index] as ConversationItem)
          : {
              id: action.itemId,
              kind: "reasoning",
              summary: "",
              content: "",
            };
      const updated: ConversationItem = {
        ...base,
        content: mergeStreamingText(
          "content" in base ? base.content : "",
          action.delta,
        ),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    case "appendPlanDelta": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      const base =
        index >= 0 && list[index].kind === "tool"
          ? list[index]
          : {
              id: action.itemId,
              kind: "tool",
              toolType: "plan",
              title: "Plan",
              detail: "",
              status: "in_progress",
              output: "",
            };
      const existingOutput = base.kind === "tool" ? (base.output ?? "") : "";
      const updated: ConversationItem = {
        ...(base as ConversationItem),
        kind: "tool",
        toolType: "plan",
        title: "Plan",
        detail: "Generating plan...",
        status: "in_progress",
        output: mergeStreamingText(existingOutput, action.delta),
      } as ConversationItem;
      const next = index >= 0 ? [...list] : [...list, updated];
      if (index >= 0) {
        next[index] = updated;
      }
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    case "appendToolOutput": {
      const list = state.itemsByThread[action.threadId] ?? [];
      const index = list.findIndex((entry) => entry.id === action.itemId);
      if (index < 0 || list[index].kind !== "tool") {
        return state;
      }
      const existing = list[index];
      const updated: ConversationItem = {
        ...existing,
        output: mergeStreamingText(existing.output ?? "", action.delta),
      } as ConversationItem;
      const next = [...list];
      next[index] = updated;
      return {
        ...state,
        itemsByThread: {
          ...state.itemsByThread,
          [action.threadId]: prepareThreadItems(next, { maxItemsPerThread: state.maxItemsPerThread }),
        },
      };
    }
    default:
      return state;
  }
}
